### ISSUE TITLE
Supporting Swift 4

### ISSUE THREAD

**Issue by AhmadFayyas** [MoathOthman/MOLH#10]
So far, it works in conjunction of letting the "Swift Language Version" to be 3.2 even with Swift 4 projects, otherwise I will start seeing compile errors in many library files. However, shall we migrate it to support Swift 4?

**Comment by MoathOthman** [comment]
That would be great , we can have a release fir swift 4 and fix swift3.2 release after we figure out the textview issue if we could.
Lets keep this issue around since there are a couple of other issues pointed in the main blog that i would like to address first.
What do you think?

Sent from my iPhone

On Apr 29, 2018, at 9:14 AM, Ahmad Fayyas <notifications@github.com<mailto:notifications@github.com>> wrote:


So far, it works in conjunction of letting the "Swift Language Version" to be 3.2 even with Swift 4 projects. However, shall we migrate it to support Swift 4?

**Comment by MoathOthman** [comment]
implemented.
