### ISSUE TITLE
Text Field placeholder direction is not updated first time when we change the language in both rtf and ltr cases.

### ISSUE THREAD

**Issue by zahidshaikh795** [MoathOthman/MOLH#26]
![simulator screen shot - iphone x - 2018-09-17 at 14 33 19](https://user-images.githubusercontent.com/26552136/45614295-b03d6e00-ba86-11e8-9b3c-49162f71f48c.png)
![simulator screen shot - iphone x - 2018-09-17 at 14 33 14](https://user-images.githubusercontent.com/26552136/45614314-bf242080-ba86-11e8-84b9-09aa1628b973.png)
![simulator screen shot - iphone x - 2018-09-17 at 14 31 39](https://user-images.githubusercontent.com/26552136/45614326-c9461f00-ba86-11e8-9fbc-964b34d5e980.png)
![simulator screen shot - iphone x - 2018-09-17 at 14 31 31](https://user-images.githubusercontent.com/26552136/45614339-d6630e00-ba86-11e8-931d-d8a8ad8186b9.png)

Every thing is working fine but the text field placeholder direction is not changing for the first time we change the language.If I relaunch the  app then its direction changes to the one I selected before.

**Comment by MoathOthman** [comment]
hey @zahidshaikh795 I am working on this one , I think I have a solution for it at least , you should though get the alignment correctly when you switch though , you need to set the uitextfield tag to less than zero.

**Comment by zahidshaikh795** [comment]
Settting the uitextfield tag to less than zero doesn't affect anything.
When I switch the language the ui of textfield doesn't flip. But if I run the project again then its ui is perfectly fine. Why it is not working only in case of text field.

**Comment by MoathOthman** [comment]
Textfield is different since it is an input control and not just a display so we need to take in consideration the keyboard language .
Are you sure you have the latest code, currently, am not sure if the latest release point to the latest in master!!


Sent from my iPhone

On Sep 18, 2018, at 2:26 PM, Zahid Shaikh <notifications@github.com<mailto:notifications@github.com>> wrote:


Settting the uitextfield tag to less than zero doesn't affect anything.
When I switch the language the ui of textfield doesn't flip. But if I run the project again then its ui is perfectly fine. Why it is not working only in case of text field.

**Comment by zahidshaikh795** [comment]
I have installed the pod at least one week ago.It would be really appreciable if you let me know when you update the project.

**Comment by MoathOthman** [comment]
@zahidshaikh795 I created a PR with a fix for the textfield issue, you may use 26.textfield.issue branch and tell me how it goes with , and then if its alright I will merge it . please try it as soon as possible.

**Comment by MoathOthman** [comment]
fixed in [0936](https://github.com/MoathOthman/MOLH/tree/093639483264892f74949e204f6fdfccbeb25d8b)
